### ISSUE TITLE
サイト上のダウンロードボタンが動作しない

### ISSUE THREAD

**Issue by munierujp** [kkosuge/editaro#4]
https://editaro.com/ のダウンロードボタンを押しても、 https://editaro.com/# に移動するだけでダウンロードが開始されません。

OS：macOS Mojave 10.14.1
ブラウザ：Chrome バージョン: 71.0.3578.98（Official Build） （64 ビット）

**Comment by munierujp** [comment]
さきほど試したところダウンロードできました。ネットワークの調子が悪かっただけかもしれません。すみません 🙇

**Comment by kkosuge** [comment]
すみません返信が遅くなりました :bow:
ダウンロードボタンを押した直後に JavaScript で GitHub の releases から最新のバージョンのダウンロードリンクを取得して遷移させるということをやっているのですが、どうも Github の API を叩くときに 403 などで失敗することがあるようです。

その場合、`/#` に移動するだけで、ダウンロードが行われないという現象になりました。
GitHub の API データをキャッシュするか、API が失敗したときにメッセージを表示するか、何かしらの対策を行おうと思います。

**Comment by kkosuge** [comment]
GitHub の Public API には 1時間に60回制限があるため、おそらくそれに引っかかっていたようでした。取り急ぎ JavaScript を使わずに、直リンクに変更しました。
